@startuml

class Oystercard {
    MIN_REQUIRED_AMOUNT
    MAX_BALANCE
    BALANCE_OVERFLOW_MGS
    INSUFFICIENT_FUNDS_MSG
    ..
    balance
    ..
    + top_up(sum)
    + touch_in(station)
    + touch_out(station)
    + in_journey?()
    - deduct(sum)
}

class Station {
    name
    zone
    + initialize(name)
    + get_zone(filename=)
}

class Journey {
    + initialize(entry_station, exit_station)
    + calculate_fare()
    + complete?()
}

Oystercard -- Station
Journey "1" --> "2" Station: stations
Oystercard "1" --> "0..*" Journey: journeys



@enduml